//! Java orchestrator test generation

use crate::orchestrate::*;
use crate::spec::Spec;
use std::collections::HashMap;

use super::{find_connections, to_pascal};

pub fn generate_integration_tests(orch: &Orchestrator, _specs: &HashMap<String, Spec>) -> String {
    let mut out = String::new();
    let class_name = to_pascal(&orch.id);

    out.push_str(&format!(
        "// Integration tests for orchestrator: {}\n// Generated by IMACS\n\nimport org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.*;\n\npublic class {}IntegrationTests {{\n",
        orch.id, class_name
    ));

    // Happy path test
    out.push_str(&format!(
        "    @Test\n    public void test{}_happyPath() {{\n        var input = new {}Input();\n        // TODO: Set input fields\n\n        var result = {}.evaluate(input);\n        assertNotNull(result);\n    }}\n\n",
        class_name, class_name, class_name
    ));

    // Branch tests
    for step in &orch.chain {
        if let ChainStep::Branch(branch) = step {
            for case_name in branch.cases.keys() {
                out.push_str(&format!(
                    "    @Test\n    public void test{}_branch{}_case{}() {{\n        var input = new {}Input();\n        var result = {}.evaluate(input);\n        assertNotNull(result);\n    }}\n\n",
                    class_name, to_pascal(&branch.id), to_pascal(case_name), class_name, class_name
                ));
            }
        }
    }

    // Gate tests
    for step in &orch.chain {
        if let ChainStep::Gate(gate) = step {
            out.push_str(&format!(
                "    @Test\n    public void test{}_gate{}_fails() {{\n        var input = new {}Input();\n        assertThrows(IllegalStateException.class, () -> {}.evaluate(input));\n    }}\n\n",
                class_name, to_pascal(&gate.id), class_name, class_name
            ));
        }
    }

    out.push_str("}\n");
    out
}

pub fn generate_contract_tests(orch: &Orchestrator, specs: &HashMap<String, Spec>) -> String {
    let mut out = String::new();
    let class_name = to_pascal(&orch.id);

    out.push_str(&format!(
        "// Contract tests for orchestrator: {}\n\nimport org.junit.jupiter.api.Test;\n\npublic class {}ContractTests {{\n",
        orch.id, class_name
    ));

    let connections = find_connections(&orch.chain);
    for (from_spec, to_spec, _) in connections {
        if specs.contains_key(&from_spec) && specs.contains_key(&to_spec) {
            out.push_str(&format!(
                "    @Test\n    public void testContract_{}_to_{}() {{\n        // Verify {} output is compatible with {} input\n    }}\n\n",
                from_spec, to_spec, from_spec, to_spec
            ));
        }
    }

    out.push_str("}\n");
    out
}
